config/routes.rb
Rails.application.routes.draw do
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  resources :notifications
  # the page root
  root to:'microposts#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"

    resources :users
    resources :microposts do
      resources :comments
      member do
        post :like_unlike
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions
  
  # get 'microposts/users/:id/get_following', to: "users#get_following"

  # routes for Users
  resources :users do
    resources :microposts
    
    member do
      get :get_following
      get :get_followers
    end
    
    collection do
      get :all_users
    end
  end
  
  resources :microposts do
    collection do
      get 'search'
      get :browse
    end

    resources :comments do
      member do
        get :delete_comment
      end
    end

    member do
      get :like
      get :unlike
      get :like_unlike
      get :static_map
    end
  end
  


  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    
    authenticated :user do
      root 'microposts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'static_pages#home', as: :unauthenticated_root
    end

  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/edit', to: 'users#edit', as: :edit_profile 
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :micropost
  belongs_to :user
  has_one :notification, dependent: :destroy
  validates :content, presence: true, length: { maximum: 200 }
  
  after_create_commit { MicropostBrodcastJob.perform_later(self, "comment", "true", self.user_id) }
  after_destroy_commit { MicropostBrodcastJob.perform_now(self, "comment", "false", self.user_id) }
  
  after_destroy :destroy_mentions_notifications
  
  acts_as_mentioner
  include MentionConcernUtilities

  #TODO research:
  # 1. Should we generate HTML in model?
  # 2. Is a good idea to check first for mentions in comment then save it?
  def save_with_hooks?
    modified_content, user_names = check_for_mentionable(self)
    self.content = modified_content if user_names.present?
    
    if self.save
      # if @names present than we have mentions
      # create mentions and notifications
      # else just create notification for the comment
      if user_names.present?
        create_mentions(user_names, self)
      else
        Notification.create(user_id: micropost.user_id, notified_by_id: user_id, micropost_id: micropost.id, comment_id: id, notice_type: "comment")
      end
      
      return true
    else
      return false
    end
  end
  
  private

  def destroy_mentions_notifications
    user_ids = self.mentionees(User).map(&:id)
    Notification.where(read: false, notice_type: "mention", user_id: user_ids, comment_id: self.id).destroy_all if user_ids.present?
  end

end

app/controllers/api/comments_controller.rb
module Api
class CommentsController < BaseController
  before_action :auth_only!
  
  def index
    @comments = Comment.where(micropost_id: params[:micropost_id]).includes(:user)
    @send_comments = []
    @comments.each do |c|
      comment = {
        id: c.id,
        user_id: c.user_id,
        micropost_id: c.micropost_id,
        content: c.content,
        user_name: c.user.user_name
      }
      @send_comments << comment
    end
    render json: @send_comments
  end
  
  def destroy
    @comment = Comment.where(id: params[:id]).first
    if current_user.id == @comment.user_id
      Comment.destroy(params[:id])
      render json: { message: "OK" }
    else
      render json: {message: "ERROR"}, status: :unprocessable_entity
    end
  end
  
  def update
    @comment = Comment.where(id: params[:id]).first
    if @comment.update_attributes(comment_params)
      comment = {
        id: @comment.id,
        user_id: @comment.user_id,
        micropost_id: @comment.micropost_id,
        content: @comment.content,
        user_name: @comment.user.user_name
      }
      render json: comment
    else
      render json: @comment.error, status: :unprocessable_entity
    end
  end
  
  def create
    params[:comment].merge!({user_id: current_user.id})
    params[:comment].merge!({micropost_id: params[:micropost_id]})
    @comment = Comment.new(comment_params)
    if @comment.save
      comment = {
        id: @comment.id,
        user_id: @comment.user_id,
        micropost_id: @comment.micropost_id,
        content: @comment.content,
        user_name: @comment.user.user_name,
      }
      render json: comment
    else
      render json:@micropost.errors, status: :unprocessable_entity
    end
  end
  
  def new
    @comment = Comment.new
    render json: @comment
  end
  
  protected 
  
  def comment_params
    params.require(:comment).permit( :user_id, :micropost_id, :content, :user_name )
  end
  
end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :load_micropost
  before_action :load_comment, except: [:index, :new]
  load_and_authorize_resource
  
  def edit
  end
  
  def index
    @comments = @micropost.comments.includes(:user).order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end
  
  def show
  end
  
  def new
    @comment = Comment.new(micropost_id: @micropost.id, user_id: current_user.id)
  end
  
  def create
    params[:comment].merge!({user_id: current_user.id})
    params[:comment].merge!({micropost_id: params[:micropost_id]})
    @comment = Comment.new(comment_params)
    
    @result = @comment.save_with_hooks?
    
    flash[:error] = @comment.errors.full_messages.to_sentence if @result == false
    
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end
  
  def update
    @comment.update(comment_params)
    redirect_to micropost_path(@micropost)
  end
  
  def destroy
    @comment.destroy!
    
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end
  
  def delete_comment
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :micropost_id, :user_id)
    end
    
    def load_micropost
      @micropost = Micropost.where(id: params[:micropost_id]).first
      authorize! :read, @micropost
    end
    
    def load_comment
      @comment = Comment.find_by(id: params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.post-comment{id: "micropost_#{micropost.id}_comment_#{comment.id}"}
  = image_tag comment.user.image.user_avatar, class: "profile-photo-sm"
  %p
    = raw "#{link_to comment.user.user_name, profile_path(comment.user.user_name)}"
    
    .comment-content
      = raw comment.content

    - if comment.user == current_user
      = link_to delete_comment_micropost_comment_path(micropost, comment), remote: true do
        %span(class="glyphicon glyphicon-remove delete-comment-link")

app/views/comments/_delete_comment.html.haml
#deleteComment-modal.modal.fade.hmodal-danger{"aria-hidden" => "true", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .color-line
      .modal-header.set-padding-top-10.set-padding-bottom-10
        %h4.modal-title{style: "text-align: left;"}
          Delete Comment
      .modal-body
        %h3.text-center
          = "Are you sure you want to delete the comment?"
          %br
          = raw "'#{comment.content}'"
        %br
        .text-center
          = link_to "Yes, delete comment!", micropost_comment_path(micropost, comment), data: {post_id: micropost.id, value: micropost.comments.count}, method: :delete, remote: true, id: "delete-#{comment.id}", class: "btn btn-danger delete-comment"
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Kepp browsing!

app/views/comments/_form.html.erb
<%= form_for [@micropost, @comment] do |f| %>
  <%= f.hidden_field :micropost_id, value: f.object.micropost_id %>
  <%= f.hidden_field :user_id, value: f.object.user_id %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="comment-message" class="form-row">
  <%= f.text_area :content, placeholder: "Whats on your mind?", id: "comment" %>
  </div>
  <%= f.submit "Submit comment", class: "btn btn-primary", id: "commentSubmit2" %>
<% end %>

app/views/comments/_old_comment.html.haml
.comment
  .user-name
    = raw "#{link_to comment.user.user_name, profile_path(comment.user.user_name)}:"
  .comment-content
    = raw comment.content
  - if comment.user == current_user
    = link_to delete_comment_micropost_comment_path(micropost, comment), remote: true do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/_oldcreate.js.haml
$('#comments_#{@micropost.id}').append("#{j render 'comments/comment', micropost: @micropost, comment: @comment }");
$('#comment_content_#{@micropost.id}').val('');

app/views/comments/create.js.haml
- if @result == true
  $("#comment_content_#{@micropost.id}").val('');
  $("#comment_content_#{@micropost.id}").blur();
  -# 
  -# Append.comment_count += 1;
  -# $(Append.id).attr('data-value', Append.comment_count);
  -# 
  -# if (Append.comment || Append.open){
  
  $("#comments_#{@micropost.id}").append("#{j render 'comments/comment', micropost: @micropost, comment: @comment}"); 
  
  -# } else if ((Append.comment && Append.open) === false && Append.link === true) {
  -# 
  -# $('#comments_' + Append.micropost_id).append("<div class='paginator' id='#comments-paginator-" + Append.micropost_id + "'><a class='more-comments' id='more_comments_" + Append.micropost_id + "' data-micropost-id='" + Append.micropost_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/microposts/" + Append.micropost_id + "/comments'>view all " + Append.comment_count + " comments</a></div>"); 
  -# ClickableCommentsLink();
  -# 
  -# } else if ((Append.comment && Append.open && Append.link) === false) {
  -# 
  -# $("#more_comments_#{@micropost.id}").html("view all #{@micropost.comments.count} comments");
  -# 
  -# }

- else
  $("#comment_error_#{@micropost.id}").html("#{escape_javascript(render("shared/flash_notice"))}");
  $("#comment_error_#{@micropost.id}").removeClass('hidden');
  
  if((".flash_notice:visible").length > 0){
  
  $(".alert").fadeOut(7000, function() {  
  $(".alert").remove();
  
  });
  }

app/views/comments/delete_comment.js.haml
$("#delete_comment").html("#{j render partial: 'comments/delete_comment', locals: {comment: @comment, micropost: @micropost}}");
$("#delete_comment").removeClass('hidden');
$("#deleteComment-modal").modal('show');
$("#deleteComment-modal").on('shown.bs.modal', function () {
$(".iradio_square-green.checked").removeClass("checked");
});
$(document).ready(window.ready);
$(document).on("page:load", window.ready);

app/views/comments/destroy.js.haml
$('#deleteComment-modal').modal('hide');
-# $('body').removeClass('modal-open');
$('.modal-backdrop').remove();
$('#comments_#{@micropost.id}').html("#{j render @micropost.comments, micropost: @micropost, comment: @comment}");
Append.comment_count -= 1;

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', micropost_path(@micropost) %> |
<%= link_to 'Back', micropost_path(@micropost) %>

app/views/comments/index.html.haml
= render @comments, micropost: @micropost

app/views/comments/new.html.erb
<h1>New Comment</h1>
<center>
  <%= render 'form' %>
  <%= link_to 'Back', micropost_path(@micropost),  class: "btn btn-info" %>
</center>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_micropost_comment_path(@micropost, @comment) %> |
<%= link_to 'Back', micropost_comments_path(@micropost) %>