config/routes.rb
Rails.application.routes.draw do
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  resources :notifications
  # the page root
  root to:'microposts#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"

    resources :users
    resources :microposts do
      resources :comments
      member do
        post :like_unlike
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions
  
  # get 'microposts/users/:id/get_following', to: "users#get_following"

  # routes for Users
  resources :users do
    resources :microposts
    
    member do
      get :get_following
      get :get_followers
    end
    
    collection do
      get :all_users
    end
  end
  
  resources :microposts do
    collection do
      get 'search'
      get :browse
    end

    resources :comments do
      member do
        get :delete_comment
      end
    end

    member do
      get :like
      get :unlike
      get :like_unlike
      get :static_map
    end
  end
  


  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    
    authenticated :user do
      root 'microposts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'static_pages#home', as: :unauthenticated_root
    end

  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/edit', to: 'users#edit', as: :edit_profile 
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Followers -> who follows the user
  # Following -> who the user is following
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  
  validates :user_name, presence: true, uniqueness: true, length: { minimum: 4, maximum: 40 }
  validates :email, presence: true
  
  # Socialization Gem
  acts_as_mentionable
  
  # Acts as Voter gem
  acts_as_voter
  
  include TokenAuthenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook, :twitter, :instagram]

  before_save :ensure_authentication_token

  mount_uploader :image, ImageUploader
  mount_uploader :timeline_cover, TimelineCoverUploader

  def self.from_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first_or_initialize.tap do |user|
      user = User.load_user_from_omniauth(user, auth)
    end
  end

  def feed
    Micropost.where("user_id = ?", id)
  end
  
  def follow(user_id)
    if follow = following_relationships.create(following_id: user_id)
      Notification.create(user_id: user_id, notified_by_id: self.id, notice_type: 'follow', follow_id: follow.id )
      return true
    else
      return false
    end
  end
  
  def unfollow(user_id)
    if follow = following_relationships.find_by(following_id: user_id)
      follow.destroy!
      Notification.where(user_id: user_id, notified_by_id: self.id, notice_type: 'follow', follow_id: follow.id).destroy_all
      return true
    else
      return false
    end
  end
  
  # Function tries to like a micropost
  # If successfully liked a micropost a notification is created as well
  def try_like(micropost)
    if self.likes(micropost)
      
      like = micropost.get_upvotes.where(voter_id: self.id).pluck(:id).first
      Notification.create(user_id: micropost.user_id, notified_by_id: self.id, micropost_id: micropost.id, like_id: like, notice_type: "like")
      MicropostBrodcastJob.perform_later(micropost, "like", "true", self.id)
      return true
    else
      return false
    end
  end
  
  # Function that tries to unlike a micropost
  # If unlike'd successfully, we destroy the created notification (notification was created when user liked) as well
  def try_unlike(micropost)
    like_id = micropost.get_upvotes.where(voter_id: self.id).pluck(:id).first
    if self.dislikes(micropost)
      Notification.where(like_id: like_id).destroy_all
      MicropostBrodcastJob.perform_later(micropost, "like", "false", self.id)
      return true
    else
      return false
    end
  end
  
  # Returns an array of arrays with 2 elements, first element - notificaton type, second element - created_at
  # ex [ ['like', 'date'], [comment, 'date'], ..]
  def activities
    return Notification.activities(self.id)
  end
  
  # Returns all the user_names that SELF (user) is following
  def following_user_names
    return following.pluck(:user_name)
  end
  
  def following_user_ids
    self.following_relationships.pluck(:following_id)
  end
  
  def followers_user_ids
    self.follower_relationships.pluck(:follower_id)
  end
  
  # Returns 5 users that a user is not following
  def follow_recomandations
    return User.where.not(id: following_user_ids << self.id).limit(5).order('RANDOM()')
  end
  
  # Returns SELF's (user) microposts paginated and eager loaded
  def displayed_microposts(page)
    microposts.displayed(page)
  end
  
  def online_followings
    online_followings_ids = following_user_ids & $redis_onlines.keys.map(&:to_i)
    return User.where(id: online_followings_ids).to_a
  end
  
  def is_online?
    return true if $redis_onlines.keys.include?("#{self.id}")
  end

  private

    def self.load_user_from_omniauth(user, auth)
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email if user.email.blank?
      user.email = auth.info.nickname + "@#{auth.provider}.com" if user.email.blank?
      user.password = Devise.friendly_token[0,20] if user.password.blank?
      user.remote_image_url = auth.info.image.gsub('http://','https://') if user.remote_image_url.blank?

      name = auth.info.name.split(" ")
      user.first_name = name[0] if user.first_name.blank?
      user.last_name = name[1] if user.last_name.blank?
      user.user_name = name.join("_") if user.user_name.blank?
      
      return user
    end

end

app/controllers/api/users_controller.rb
module Api
class UsersController < BaseController
  before_action :auth_only!, except: [:create]
 # load_and_authorize_resource
 
  def create
    @user = User.new(user_params)
    if @user.save
      # UserMailer.signup_confirmation(@user).deliver_now
      render_or_false(@user, "api/users/show")
    else
      render json: @user.errors.full_messages.to_sentence, status: 400 and return
    end
  end

  def update
    @user = current_user
    render json: "User not found", status: 400 and return if @user.blank?
    
    if @user.update_attributes(user_params)
      render_or_false(@user, "api/users/show")
    else
      render json: @user.errors.full_messages.to_sentence, status: 400 and return
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render_or_false(@user, "api/users/show")
  end

  protected
  def user_params
    params.require(:user) \
          .permit( :email, :password, :password_confirmation, :image,
                   :first_name, :last_name, :about_me)
  end
end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "devise"
  def new
    super
  end

  def create
    super
    if resource.save
      sign_in resource
    end
  end

  def update
    super
  end
  
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_user, only: [:show]
  load_and_authorize_resource
  layout "timeline"
  
  def show
    @microposts = @user.displayed_microposts(params[:page] || "1")
    @activities = @user.activities
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    prepare_params
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully updated!"
      redirect_to profile_path(@user.user_name)
    else
      @user.reload
      render 'edit'
    end
  end
  
  def get_following
    following = @user.following_user_names
    respond_to do |format|
      format.js { render :json => following }
    end
  end
  
  def get_followers
    @users = @user.followers
  end
  
  def all_users
    @users = User.all
  end

  private
    def user_params
      params.require(:user).permit( :email, :password, :password_confirmation, :image, :remove_image, :user_name, :first_name, :last_name, :bio, :timeline_cover, :user_name)
    end

    def load_user
      if params[:id].present?
        @user = User.where(id: params[:id]).first
      else
        @user = User.where(user_name: params[:user_name]).first
      end
      redirect_to root_path and return if @user.blank?
    end

    def prepare_params
      if params[:user][:password].blank? && \
        params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
    end

end

app/views/users/_followers.html.haml
#users-modal.modal.fade.hmodal-danger{"aria-hidden" => "true", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .color-line
      .modal-header.set-padding-top-10.set-padding-bottom-10
        %h4.modal-title{style: "text-align: left;"}
          = users_type
      .modal-body
        %h3.text-center
        %br
        %ul
          - users.each do |user|
            %li
              = image_tag user.image, size: "100x100"
              = link_to "#{user.first_name} #{user.last_name}", profile_path(user.user_name)
        .text-center
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Check feed

:javascript
  $('#users-modal').on('hidden.bs.modal', function (e) {
    $(this).remove();
  });

app/views/users/_user_info.html.erb
<%=link_to (image_tag(@user.image, size: "100x100")), @user %>
<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
<span><%= pluralize(user_micropost_count, "micropost") %></span>

app/views/users/all_users.js.haml
$("#all_users").html("#{j render partial: 'users/followers', locals: { users: @users, users_type: "All Users"}}");
$("#all_users").removeClass('hidden');
$("#users-modal").modal('show');
$("#users-modal").on('shown.bs.modal', function () {
$(".iradio_square-green.checked").removeClass("checked");
});
$(document).ready(window.ready);
$(document).on("page:load", window.ready);

app/views/users/edit.html.haml
- provide(:title, "Edit")
.row{style: "margin-top: 100px;"}
  %h4{style: "text-align: center; margin-bottom: 30px;"}
    = "Edit Account"
    = render "shared/flash_notice"
  = form_for @user, html: {multipart: true }, validate: true do |f|
    - add_error(@user.errors.full_messages.to_sentence, 'alert') if @user.errors.any?

    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-user
      = f.email_field :email, autofocus: true, placeholder: "#{t ".email"}", autocomplete: "off", class: "form-control"
      
    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-user
      = f.text_field :user_name, autofocus: true, placeholder: "User Name", autocomplete: "off", class: "form-control"

    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-user
      = f.text_field :first_name, autofocus: true, placeholder: "First Name", autocomplete: "off", class: "form-control"

    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-user
      = f.text_field :last_name, autofocus: true, placeholder: "Last Name", autocomplete: "off", class: "form-control"

    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-lock
      = f.password_field :password, autocomplete: "off", placeholder: "#{t ".new_password"}", class: "form-control"

    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-lock
      = f.password_field :password, autocomplete: "off", placeholder: "#{t ".confirm_new_password"}", class: "form-control"
      
    .form-group.input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-address-card
      = f.text_area :bio, autocomplete: "off", placeholder: "Bio", class: "form-control"

    .form-group
      .fileupload.fileupload-new{data: {provides: 'fileupload' }}
        .fileupload-preview.thumbnail.thumb-preview{style: "width: 80px; height: 77px"}
          - if @user.try(:image).present?
            = image_tag @user.image
          - else
            = image_tag "fallback/user.gif"
        %div
          %span.btn.btn-file.btn-default.btn-sm
            %span.fileupload-new
              %span.glyphicon.glyphicon-picture
              = t ".image"
            %span.fileupload-exists
              %span.glyphicon.glyphicon-open
              = t '.change'
            = f.file_field :image
          = link_to "#", class: "btn fileupload-exists btn-danger btn-sm", data: {dismiss: 'fileupload'} do
            %span.glyphicon.glyphicon-remove
            = t '.remove'

    - if @user.try(:image).present?
      .form-group
        .checkbox
          %label
            = f.check_box :remove_image
            = t ".remove_image"

    .form-group
      = f.submit (t ".button_update"), class: "btn btn-success full-width"

    .form-group
      = link_to (t ".button_sign_out"), signout_path, class: "btn btn-default"

:javascript
  $("#edit_user_#{@user.id}").enableClientSideValidations();

app/views/users/get_followers.js.haml
$("#following_users").html("#{j render partial: 'users/followers', locals: { users: @users, users_type: "Followers"}}");
$("#following_users").removeClass('hidden');
$("#users-modal").modal('show');
$("#users-modal").on('shown.bs.modal', function () {
$(".iradio_square-green.checked").removeClass("checked");
});
$(document).ready(window.ready);
$(document).on("page:load", window.ready);

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/old_show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if can?(:edit, @user)
            = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button'
          - else
            - if current_user_is_following(current_user.id, @user.id)
              = link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post
            - else
              = link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @microposts.count, 'post'
        %p
          = pluralize @followers, 'follower'
        %p
          = pluralize @following, 'following'

.posts{id: "my-microposts"}
  = render @microposts
.pagi_di{id: "infinite-scrolling"}
  = will_paginate @microposts

:javascript
  window.writeit.scrolling.inf();
  window.writeit.microposts.more_comments();
  

app/views/users/show.html.haml
- if current_user == @user
  = render partial: "microposts/form"
- else
  .create-post

.microposts{id: "my-microposts"}
  = render "shared/flash_notice"
  = render @microposts

.pagi_di{id: "infinite-scrolling"}
  = will_paginate @microposts

#delete_comment
:javascript
  window.writeit.microposts.use_mentioner("#{current_user.id}");
  window.writeit.scrolling.inf();

app/views/users/show.js.haml
$('#my-microposts').append("#{j render @microposts}");
- if @microposts.next_page
  $('.pagination').replaceWith("#{j will_paginate @microposts}");
- else
  $(window).off('scroll');
  $('.pagination').remove();