config/routes.rb
Rails.application.routes.draw do
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  resources :notifications
  # the page root
  root to:'microposts#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"

    resources :users
    resources :microposts do
      resources :comments
      member do
        post :like_unlike
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions
  
  # get 'microposts/users/:id/get_following', to: "users#get_following"

  # routes for Users
  resources :users do
    resources :microposts
    
    member do
      get :get_following
      get :get_followers
    end
    
    collection do
      get :all_users
    end
  end
  
  resources :microposts do
    collection do
      get 'search'
      get :browse
    end

    resources :comments do
      member do
        get :delete_comment
      end
    end

    member do
      get :like
      get :unlike
      get :like_unlike
      get :static_map
    end
  end
  


  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    
    authenticated :user do
      root 'microposts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'static_pages#home', as: :unauthenticated_root
    end

  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/edit', to: 'users#edit', as: :edit_profile 
  mount ActionCable.server => '/cable'
end

app/helpers/newsfeed_helper.rb
module NewsfeedHelper

end

app/views/layouts/newsfeed/sidebar_left/_chat_block.html.haml
- online_followings = current_user.online_followings

#chat-block
  - if online_followings.present?
    %div{id: "online-title", class: "title-online"}
      = "Online followings"
    %ul.online-users.list-inline
      = render partial: "layouts/newsfeed/sidebar_left/online_user", collection: online_followings
  - else
    %div{id: "online-title", class: "title-offline"}
      = "All followings offline"
    %ul.online-users.list-inline

app/views/layouts/newsfeed/sidebar_left/_links.html.haml
%ul.nav-news-feed
  %li
    %i.icon.ion-ios-paper
    %div
      = link_to "My Newsfeed", profile_path(current_user.user_name)
  %li
    %i.icon.ion-ios-people-outline
    %div
      = link_to "Followers", get_followers_user_path(current_user), remote: true
  %li
    %i.icon.ion-ios-people
    %div
      = link_to "All Users", all_users_users_path, remote: true

  -# %li
  -#   %i.icon.ion-chatboxes
  -#   %div
  -#     %a{:href => "#"} Messages
  -# %li
  -#   %i.icon.ion-images
  -#   %div
  -#     %a{:href => "#"} Images
  -# %li
  -#   %i.icon.ion-ios-videocam
  -#   %div
  -#     %a{:href => "#"} Videos

#following_users.hidden
#all_users.hidden

app/views/layouts/newsfeed/sidebar_left/_online_user.html.haml
%li{id: "online_user_#{online_user.id}"}
  = link_to profile_path(online_user.user_name) do
    = image_tag online_user.image.user_avatar, class: "img-responsive profile-photo"
    %span.online-dot

app/views/layouts/newsfeed/sidebar_left/_profile_card.html.haml
.profile-card{style: "background: linear-gradient(to bottom, rgba(39, 170, 225, 0.8), rgba(28, 117, 188, 0.8)), url(#{current_user.timeline_cover.newsfeed_cart}) no-repeat;"}
  = image_tag current_user.image.user_avatar, class: "profile-photo"
  -# %img.profile-photo{:alt => "user", :src => "http://placehold.it/300x300"}/
  %h5
    = link_to current_user.user_name, profile_path(current_user.user_name), class: "text-white"
  %i.ion.ion-android-person-add
  .current_user_followers_count{id: "current_user_followers_count_#{current_user.id}"}
    = pluralize current_user.followers.count, 'follower'