config/routes.rb
Rails.application.routes.draw do
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  resources :notifications
  # the page root
  root to:'microposts#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"

    resources :users
    resources :microposts do
      resources :comments
      member do
        post :like_unlike
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions
  
  # get 'microposts/users/:id/get_following', to: "users#get_following"

  # routes for Users
  resources :users do
    resources :microposts
    
    member do
      get :get_following
      get :get_followers
    end
    
    collection do
      get :all_users
    end
  end
  
  resources :microposts do
    collection do
      get 'search'
      get :browse
    end

    resources :comments do
      member do
        get :delete_comment
      end
    end

    member do
      get :like
      get :unlike
      get :like_unlike
      get :static_map
    end
  end
  


  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    
    authenticated :user do
      root 'microposts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'static_pages#home', as: :unauthenticated_root
    end

  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get ':user_name', to: 'users#show', as: :profile
  get ':user_name/edit', to: 'users#edit', as: :edit_profile 
  mount ActionCable.server => '/cable'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  # Socialization Gem
  acts_as_mentioner
  
  # Acts as Votable gem
  acts_as_votable
  
  # searchkick
  attr_accessor :full_street_address
  
  scope :ordered, -> { order(created_at: :desc) }
  scope :of_followed_users, -> (following_users) { where(user_id: following_users).order(created_at: :desc) }
  scope :displayed, -> (page) { includes(:user, comments: :user).paginate(page: page.to_i, per_page: 3).ordered }
  
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :city, presence: true
  validates :street, presence: true
  validate  :picture_size
  
  geocoded_by :full_street_address
  after_validation :geocode, if: :street_address_changed?
  
  reverse_geocoded_by :latitude, :longitude, address: :full_street_address 
  before_validation :reverse_geocode, if: :street_address_empty?
  
  after_create_commit {NewMicropostBrodcastJob.perform_now(self, "first")}
  
  def full_street_address
    [street, number, city].compact.join(', ')
  end
  
  def full_street_address=(val)
    array_address = val.split(", ")
    if array_address.present?
      self.street = array_address[0]
      self.city = array_address[1]
      self.number = (self.street.match(/\s\d+$/)[0]).to_i if self.street.match(/\s\d+$/).present?
      if self.number.present?
        self.street = self.street.gsub(self.number.to_s, "")
      end
    end
  end
  
  def street_address_empty?
    return self.street.blank?
  end
  
  def street_address_changed?
    street_changed? || number_changed? || city_changed?
  end
  
  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/api/microposts_controller.rb
module Api
class MicropostsController < BaseController
  before_action :auth_only!
  
  def index
    # @microposts =  Micropost.all.paginate(:page => params[:page], :per_page => 5)
    @microposts = Micropost.all.ordered.includes(:user, :likes)
    # render json: @microposts.to_json(:methods => [:image_url])
    @send_microposts = []
    current_user_id = current_user.id
    @microposts.each do |m|
      micropost = {
        id: m.id, 
        user_id: m.user_id,
        title: m.title,
        street: m.street,
        number: m.number,
        city: m.city,
        content: m.description,
        likers_count: m.likers_count,
        latitude: m.latitude.to_f.to_s,
        longitude: m.longitude.to_f.to_s,
        picture: m.picture.large.url,
        user_click_like: ((m.likes.collect(&:liker_id) & [current_user_id]).size > 0).to_s
      }
      @send_microposts << micropost
    end
    render json: @send_microposts
  end
  
  def create
    params[:micropost].merge!({user_id: current_user.id})
    @micropost =  Micropost.new(micropost_params)
    if @micropost.save
      micropost = {
        id: @micropost.id, 
        user_id: @micropost.user_id,
        title: @micropost.title,
        street: @micropost.street,
        number: @micropost.number,
        city: @micropost.city,
        content: @micropost.description,
        likers_count: @micropost.likers_count,
        latitude: @micropost.latitude,
        longitude: @micropost.longitude,
        picture: @micropost.picture.url,
        user_click_like: "false"
      }
      # comentariu
      render json: micropost
    else
      render json:@micropost.errors, status: :unprocessable_entity
    end
  end
  
  def like_unlike
    @micropost = Micropost.where(id: params[:id]).first
    if @micropost.present?
      if !current_user.likes?(@micropost)
        current_user.like!(@micropost)
        render json: {message: "OK", action: "like"}
      else
        current_user.unlike!(@micropost)
        render json: {message: "OK", action: "unlike"}
      end
    else
      render json: {message: "ERROR"}
    end
  end
  
  def update
    @micropost = Micropost.where(id: params[:id]).first
    if @micropost.update_attributes(micropost_params)
      micropost = {
        id: @micropost.id, 
        user_id: @micropost.user_id,
        title: @micropost.title,
        street: @micropost.street,
        number: @micropost.number,
        city: @micropost.city,
        content: @micropost.description,
        likers_count: @micropost.likers_count,
        latitude: @micropost.latitude,
        longitude: @micropost.longitude,
        picture: @micropost.picture.url
      }
      render json: micropost
    else
      render json: @micropost.error, status: :unprocessable_entity
    end
  end
  
  def new
    @micropost = Micropost.new
    render json: @micropost
  end
  
  def destroy
    @micropost = Micropost.where(id: params[:id]).first
    if current_user.id == @micropost.user_id
      Micropost.destroy(params[:id])
      render json: {message: "OK"}
    else
      render json: {message: "ERROR"}, status: :unprocessable_entity
    end
  end
  
  protected
  def micropost_params
    params.require(:micropost).permit( :title, :description, :street, :number, :city, :user_id, :picture, :latitude, :longitude)
  end
end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_micropost, except: [:create, :index, :search, :new, :browse]
  load_and_authorize_resource
  respond_to :html, :js
  layout "newsfeed"
  
  
  def index
    # @micropost = Micropost.new
    # if params[:user_id].present?
    #   @user = User.find_by(id: params[:user_id])
    #   @microposts = Micropost.includes(:user, comments: :user).where(user_id: params[:user_id].to_i).ordered.includes(:user)
    # else
    #   # @user = current_user
    #   user_ids = [current_user.id] + current_user.following_ids
    #   @microposts = Micropost.of_followed_users(user_ids).includes(:user, comments: :user).paginate(page: page.to_i, per_page: 3)
    # end
    @microposts = Micropost.all.displayed(params[:page] || "1")
    @follow_recomandations = current_user.follow_recomandations
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def show  
    # @comments = @micropost.comments
    # @comment = Comment.new(micropost_id: @micropost.id, user_id: current_user.id)
    # @can_delete_comments = {}
    # @comments.each do |c|
    #   @can_delete_comments[c.id] = can?(:destroy, c)
    # end
    # @can_like = Like.where(liker_id: current_user.id, likeable_id: @micropost.id).try(:size) == 0
    # @locations = Micropost.near([@micropost.latitude, @micropost.longitude], 10, order: "distance")
    # @location = nil
    # if @locations.present?
    #   @location = @locations.select do |location|
    #     location.id == @micropost.id
    #   end.first
    # end
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.new(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      respond_to do |format|
        format.html { redirect_to microposts_path }
        format.js
      end
    else
      redirect_to new_micropost_path
    end
  end
  
  def update
    if @micropost.update_attributes(micropost_params)
      redirect_to microposts_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted!"
    redirect_to microposts_path
  end

  def like
    current_user.try_like(@micropost)
    @micropost.reload
    
    respond_to do |format|
      format.html { redirect_to microposts_path }
      format.js
    end
  end
  
  def unlike
    current_user.try_unlike(@micropost)
    @micropost.reload
    
    respond_to do |format|
      format.html { redirect_to microposts_path }
      format.js
    end
  end

  def search
    if params[:search].present?
      @microposts = Micropost.search(params[:search])
    else
      @microposts = Micropost.all
    end
    
    @can_delete_microposts = {}
    @microposts.each do |m|
      @can_delete_microposts[m.id] = can?(:manage, m)
    end
  end
  
  def edit
  end
  
  def static_map
    @locations = Micropost.near([@micropost.latitude, @micropost.longitude], 10, order: "distance").where.not(id: @micropost.id)
    
    respond_to do |format|
      format.html { redirect_to microposts_path }
      format.js
    end
  end
  
  def browse
    page = params[:page] || "1"
    @microposts = Micropost.all.ordered.paginate(page: page.to_i, per_page: 3)
    user_permissions

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def load_micropost
    @micropost = Micropost.where(id: params[:id]).first
    @user = @micropost.user
  end

  def micropost_params
    params.require(:micropost).permit( :title, :description, :street, :number, :city, :picture, :likers_count )
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def display_likes(micropost)
    votes = micropost.votes_for.up.by_type("User")
    return list_likers(votes) if votes.count <= 8
    count_likers(micropost)
  end
  
  def count_likers(likes)
    return "#{likes} likes"
  end
  
  def like_button(micropost)
    if current_user.present? && current_user.voted_up_for?(micropost)
      return link_to '', unlike_micropost_path(micropost), remote: true,
                                    id: "like_#{micropost.id}",
                                    class: "like glyphicon glyphicon-heart"
    else
      return link_to '', like_micropost_path(micropost), remote: true,
                                    id: "like_#{micropost.id}",
                                    class: "like glyphicon glyphicon-heart-empty"
    end
  end
  
  def list_likers(votes)
    user_names = []
    
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  private

  def like_plural(likers)
    return ' like this' if likers.count > 1
    ' likes this'
  end
end

app/views/microposts/_form.html.haml
.create-post
  .row
    .col-md-7.col-sm-7
      .form-group
        = image_tag current_user.image.user_avatar, class: "profile-photo-md"
        %textarea#exampleTextarea.form-control{:cols => "30", :name => "texts", :placeholder => "Write what you wish", :rows => "1"}
    .col-md-5.col-sm-5
      .tools
        %ul.publishing-tools.list-inline
          %li
            %a{:href => "#"}
              %i.ion-compose
          %li
            %a{:href => "#"}
              %i.ion-images
          %li
            %a{:href => "#"}
              %i.ion-ios-videocam
          %li
            %a{:href => "#"}
              %i.ion-map
        = link_to "Publish", new_micropost_path, class: "btn btn-primary pull-right"

app/views/microposts/_likes.html.haml
.likes{id: "likes_#{micropost.id}"}
  = display_likes micropost

app/views/microposts/_micropost.html.haml
.post-content{id: "microposts_#{micropost.id}"}
  - if params[:controller] == "users"
    .post-date.hidden-xs.hidden-sm
      %h5= micropost.user.user_name
      %p.text-grey= time_ago_in_words micropost.created_at

  = image_tag micropost.picture.micropost_timeline, class: "img-responsive post-image"
  .post-container
    = image_tag micropost.user.image.user_avatar, class: "profile-photo-md pull-left"
    .post-detail
      .user-info
        %h5
          = link_to micropost.user.user_name, profile_path(micropost.user.user_name), class: "profile-link"
          %span.time-ago= time_ago_in_words micropost.created_at
          
          %span.following{class: "display_if_following_#{micropost.user_id}"}
            - # if current_user is not defined, that means this view is rendered from NewMicropostBrodcastJob
            - if current_user.blank?
              following
            - elsif current_user_is_following(current_user.id, micropost.user_id)
              following
              
        
        %p.text-muted
          = render "microposts/likes", micropost: micropost

      .reaction
        .show-map-link
          = link_to static_map_micropost_path(micropost), remote: true do
            %i.ion-map
        
        = like_button(micropost)
      
      .line-divider
      
      .post-text
        %p
          = micropost.description
      .line-divider
      
      .comments{id: "comments_#{micropost.id}"}
        - if micropost.comments.any?
          = render micropost.comments.first(4), micropost: micropost
          
          - unless micropost.comments.count <= 4
            .paginator{id: "#comments-paginator-#{micropost.id}"}
              = link_to "view all #{micropost.comments.count} comments", micropost_comments_path(micropost), remote: true, class: 'more-comments', id: "more_comments_#{micropost.id}", data: {micropost_id: "#{micropost.id}", type: "html", value: "#{micropost.comments.count}"}
        
        -# #comment_error.hidden{id: "#{micropost.id}", class: ""}
        
        .paginator.someone-is-writing{id: "writing_comment_#{micropost.id}"}
        
      .post-comment
        .current-user-image{id: "current_user_image_#{micropost.id}"}
          - if current_user.present?
            = link_to (image_tag current_user.image.user_avatar.url, class: "profile-photo-sm"), profile_path(current_user.user_name)
        = form_for [micropost, micropost.comments.build], remote: true do |f|
          = f.text_field :content, placeholder: 'Add a comment...', autocomplete: "off", class: "comment_content form-control", id: "comment_content_#{micropost.id}", data: { micropost_id: "#{micropost.id}", value: "#{micropost.comments.count}" }
          -# %input.form-control{:placeholder => "Post a comment", :type => "text", name:"comment[content]"}
  
:javascript
  window.writeit.micropost_channel.create_micropost_subscription("#{micropost.id}");

app/views/microposts/_micropost_comments.html.erb
<div class="detailBox">
  <center><div class="titleBox">
    <label>Comment Box</label>  
  </div></center>
  <div class="actionBox">
    <ul class="commentList">
      <% collection.each do |comment| %>
      <%= "#{comment.user.first_name} #{comment.user.last_name}" %>
      <li>
        <div class="commenterImage">
          <%= image_tag(comment.user.image, class: "commenterImage") %>
        </div>
        <div class="commentText">
          <p><%= comment.content %></p>
          <span class="date sub-text">
            <%= time_ago_in_words(comment.created_at) %>
            <% if current_user && can_delete_comments[comment.id] %>
              <%= link_to "eit", edit_micropost_comment_path(@micropost, comment) %> 
              <%= link_to "delete", micropost_comment_path(@micropost, comment), method: :delete,
                                               data: { confirm: "You sure?" } %>
            <% end %>
          </span>
        </div>
      </li>
      <% end %>
    </ul>
    <%= form_for [micropost, comment], html: {class: "form-inline"} do |f| %>
      <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
          <ul>
            <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group new-comment-input">
        <%= f.text_field :content, class: "form-control new-comment-input", placeholder: "Whats on your mind?" %>
      </div>
      <div class="form-group new-comment-btn">
        <%= f.submit "Add", class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/microposts/_micropost_dashboard.html.haml
.index-center
  %h2 Micropost feed
.posts-wrapper.row
  -# = render partial: "new_micropost_modal", locals: { micropost: Micropost.new }
  -# %span{"data-target" => "#test", "data-toggle" => "modal", style: "cursor: pointer; text-decoration: none;", class: "glyphicon glyphicon-plus"}
  .posts{id: "my-microposts"}
    = render @microposts
.pagi_di{id: "infinite-scrolling"}
  = will_paginate
#delete_comment.hidden
#aditional_micropost.hidden
#edit_micropost.hidden
#static_map_index.hidden
:javascript
  window.writeit.scrolling.inf();
  window.writeit.microposts.more_comments();

app/views/microposts/_micropost_form.html.erb
<%= form_for @micropost, validate: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-share"></i></span>
    <%= f.text_field :title, placeholder: "Post title... (required)", class:"form-control"  %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-map-marker"></i></span>
    <%= f.text_field :street, placeholder: "Street... (required)", class:"form-control" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-map-marker"></i></span>
    <%= f.text_field :number, placeholder: "Number...", class:"form-control" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-map-marker"></i></span>
    <%= f.text_field :city, placeholder: "City... (required)", class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Compose new micropost...", class:"form-control" %>
  </div>
  <span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  <div>
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/browse.js.haml
$('#my-microposts').append("#{j render @microposts}");
- if @microposts.next_page
  $('.pagination').replaceWith("#{j will_paginate @microposts}");
- else
  $(window).off('scroll');
  $('.pagination').remove();

app/views/microposts/create.js.haml
-# $('#microposts_#{@micropost.id}').append("#{j render 'microposts/micropost', micropost: @micropost, comment: @comment }");
-# $('#comment_content_#{@micropost.id}').val('');

app/views/microposts/edit.html.erb
<%= render 'micropost_form' %>

app/views/microposts/index.html.haml
.microposts{id: "my-microposts"}
  = render "shared/flash_notice"
  = render @microposts

.pagi_di{id: "infinite-scrolling"}
  = will_paginate

#delete_comment
#static_map_index
:javascript
  window.writeit.microposts.use_mentioner("#{current_user.id}");
  window.writeit.scrolling.inf();

app/views/microposts/index.js.haml
$('#my-microposts').append("#{j render @microposts}");
- if @microposts.next_page
  $('.pagination').replaceWith("#{j will_paginate @microposts}");
- else
  $(window).off('scroll');
  $('.pagination').remove();

app/views/microposts/like.js.haml
$('#like_#{@micropost.id}').removeClass().addClass("like glyphicon glyphicon-heart");
$('#like_#{@micropost.id}').attr("href", "#{unlike_micropost_path(@micropost.id)}")
$("#likes_#{@micropost.id}").html("#{j (render partial: 'microposts/likes', locals: { micropost: @micropost} ) }");

app/views/microposts/new.html.erb
<%= render 'micropost_form' %>

app/views/microposts/show.html.haml
= provide(:title, "Micropost")
= render @micropost
#static_map_index
:javascript
  window.writeit.microposts.use_mentioner("#{current_user.id}");